##  After learning so much in Numpy, It's time for an assignment. 

### You are a student and today is your Numpy test. The test will consist of 10 questions, purely related to code. You need to write code for the given questions.



In [1]:
import numpy as np
import pandas as pd

#### Q-1 Import Numpy and Write the code to know the version of numpy you are working on ?
Your output should look like this. <br>
NOTE : Numpy version may be different for you.

In [2]:
np.__version__

'1.21.5'

In [3]:
## write code here


In [26]:
pd.__version__

'1.4.2'

#### Q - Create a numpy array having elements from 1 to 16 (inclusive) and print it.
Your output should look like this.

In [2]:
a=np.arange(1,17)

In [3]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [6]:
## write code here


#### Q-3 You need to filter the previous array in such a way that , it only contains odd values.
Note : You have to use boolean indexing.<br>
Your output should look like this.

In [4]:
## write code here
b=a[::2]

In [5]:
b

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [6]:
b=a[a%2==1] #to get odd values

In [7]:
b

array([ 1,  3,  5,  7,  9, 11, 13, 15])

#### Q-4  Replace values that give remainder as 1 when divided by 2 from the above resulted array with 0
Your output should look like this.

In [8]:
a[a%2!=1]=0

In [9]:
a

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0])

In [7]:
## write code here
inx=[1,2,3,4,5,6,7,8]
c= np.insert(b,inx,0)

In [8]:
c

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0])

#### Q-5  Change the shape of above resulted array to 4x4.
Your output should look like this.

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [10]:
## write code here
d=np.reshape(a,(4,4))

In [11]:
d

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

#### Q-6 Stack the resulted array with itself vertically.
Your output should look like this.

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]
 [ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [13]:
## write code here
a= np.vstack((d,d))

In [14]:
a

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0],
       [ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

#### Q-7 On this vertical stacked resulted array, reverse the column order in alternate manner. column new order = [ 2,1,4,3 ]
Your output should look like this.

[[ 0  1  0  3]
 [ 0  5  0  7]
 [ 0  9  0 11]
 [ 0 13  0 15]
 [ 0  1  0  3]
 [ 0  5  0  7]
 [ 0  9  0 11]
 [ 0 13  0 15]]


In [17]:
## write code here
na=a[:,[1,0,3,2]]

In [18]:
na

array([[ 0,  1,  0,  3],
       [ 0,  5,  0,  7],
       [ 0,  9,  0, 11],
       [ 0, 13,  0, 15],
       [ 0,  1,  0,  3],
       [ 0,  5,  0,  7],
       [ 0,  9,  0, 11],
       [ 0, 13,  0, 15]])

#### Q-8 Calculate , mean , median and mode of the resulting array.
Your output should look like this.

Mean : 4.0
Median : 0.5
Mode : 0


In [20]:
## write code here
print('Mean:',np.mean(na))
print('Median:',np.median(na))

Mean: 4.0
Median: 0.5


In [32]:
mode_,idx,count_=np.unique(na.reshape(32,),return_inverse=True,return_counts=True)

In [33]:
index_=idx[np.argmax(count_)]

In [34]:
index_

0

In [35]:
mode_=na.reshape(32)[index_]

In [36]:
mode_

0

In [30]:
#another way

import statistics as st


In [38]:
st.mode(na.reshape(32))

0

In [39]:
rr=na.reshape(32,)

In [40]:
rr

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
        1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15])

In [ ]:
#dict to mode finding

In [41]:
aaa=[75,82,71,92,48,97,59,62,78,66,76]

In [47]:
dic={i:aaa.count(i) for i in aaa}

In [48]:
max_=-12
modE=None

for k,v in dic.items():
    if v>max_:
        modE=k
        max_=v

In [50]:
modE

75

#### Q-9 Create an array of 5 values , that are selected at random from the above resulted array.
Your output should look like this.

Random Element Array : [15  0  5  3  0]


In [51]:
## write code here
na

array([[ 0,  1,  0,  3],
       [ 0,  5,  0,  7],
       [ 0,  9,  0, 11],
       [ 0, 13,  0, 15],
       [ 0,  1,  0,  3],
       [ 0,  5,  0,  7],
       [ 0,  9,  0, 11],
       [ 0, 13,  0, 15]])

In [55]:
randar=np.array([np.random.choice(na.reshape(32)) for i in range(5)])

In [56]:
randar

array([15, 11,  9,  0,  0])

#### Q-10 Complete the function, that calculate the value of this function (a.k.a Binary Cross Entropy) using  Vectorization.
`Given -
    y  : a vector of N dimension,
    y^ : a vector of N dimension
    N : elements in y and y^
    Use : log base 2
    `

<img src="BCE.png" width=500>

Your output should be : 0.011179895048277702

In [57]:
def BCE(y, y_hat):
    ## write code
     
    return(y*np.log(y_hat)-(1-y)*np.log(1-y_hat)).mean()
    
    

In [58]:
y = np.array([0.13,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.1])
y_hat = np.array([0.2,0.3,0.4,0.3,0.6,0.8,0.7,0.5,0.8,0.1])

result = BCE(y, y_hat)
print(result)

0.007749312731669802


In [60]:
y.count()

AttributeError: 'numpy.ndarray' object has no attribute 'count'